FROM python:3.6-slim
RUN pip install flask pika jsonpickle requests

WORKDIR /

RUN     mkdir   /app

COPY    processor.py  /app
COPY    queue_reader.py /app
COPY    packet_reader.py /app

RUN echo "docker image for processor"
EXPOSE 9090
CMD python app/processor.py