apiVersion: v1
kind: Service
metadata:
  name: project-processor-service
  labels:
    app: project-processor-service
spec:
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 5025
  selector:
    app: project-processor