apiVersion: v1
kind: Service
metadata:
  name: extractor-service
  labels:
    app: extractor-service
spec:
  ports:
    - protocol: "TCP"
      port: 7777
      targetPort: 5024
  selector:
    app: project-extractor