apiVersion: v1
kind: Service
metadata:
  name: project-extractor
  labels:
    app: project-extractor
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 7777
      targetPort: 5024
  selector:
    app: project-extractor