FROM python:3.6-slim
RUN pip install flask pika jsonpickle requests

WORKDIR /

RUN     mkdir   /app
RUN     mkdir /app/util

COPY    queue_reader.py /app

COPY    /util/publish_logs.py /app/util

RUN echo "docker image for reader"
EXPOSE 5025
CMD python app/queue_reader.py